version: '3.7'
services:
  e2e-electron:
    image: "cypress/included:14.5.1"
    working_dir: /e2e
    command: "--browser electron --env host.yf=your-finance,host.jwtenizr=your-finance-jwtenizr"
    volumes:
      - ../e2e:/e2e
      - ../jwtenizr-files:/jwtenizr-files
      - ../your-finance-files:/your-finance-files

  e2e-chrome:
    image: "cypress/included:14.5.1"
    working_dir: /e2e
    command: "--browser chrome --env host.yf=your-finance,host.jwtenizr=your-finance-jwtenizr"
    volumes:
      - ../e2e:/e2e
      - ../jwtenizr-files:/jwtenizr-files
      - ../your-finance-files:/your-finance-files

  e2e-firefox:
    image: "cypress/included:14.5.1"
    working_dir: /e2e
    command: "--browser firefox --env host.yf=your-finance,host.jwtenizr=your-finance-jwtenizr"
    volumes:
      - ../e2e:/e2e
      - ../jwtenizr-files:/jwtenizr-files
      - ../your-finance-files:/your-finance-files

  e2e-edge:
    image: "cypress/included:14.5.1"
    working_dir: /e2e
    command: "--browser edge --env host.yf=your-finance,host.jwtenizr=your-finance-jwtenizr"
    volumes:
      - ../e2e:/e2e
      - ../jwtenizr-files:/jwtenizr-files
      - ../your-finance-files:/your-finance-files
