name: e2e-your-finance-je

on:
  push:
    branches: [ main ]

jobs:
  e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Docker
        run: make dcup-full-action

      - name: Run Cypress
        run: make cypress-electron

  e2e-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Docker
        run: make dcup-full-action

      - name: Run Cypress
        run: make cypress-chrome

  e2e-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Docker
        run: make dcup-full-action

      - name: Run Cypress
        run: make cypress-firefox

  e2e-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Docker
        run: make dcup-full-action

      - name: Run Cypress
        run: make cypress-edge
